#!/bin/sh
case $1 in
  (push) cd $HOME/.home && git add -A && git commit -m"Audo Commit Home Config" && git push;;
  (pull) cd $HOME/.home && git pull HEAD;;
  (*)   echo "How did I get in the middle of nowhere?";;
esac

